// ── Core scalar range used to define requirements ────────────────────────────
export type HealthRange = {
  min: number;
  max: number;
  optimal: number;
};

// ── Species enumerations ──────────────────────────────────────────────────────
export type PlantSpecies = "Moss" | "Fern";
export type OrganismSpecies = "Isopod" | "Springtail";

// ── Biological requirement shapes ─────────────────────────────────────────────
export type PlantRequirements = {
  lighting: HealthRange;   // 0-100 scale
  humidity: HealthRange;   // 0-100 scale
  temperature: HealthRange; // °C
};

export type OrganismRequirements = {
  temperature: HealthRange;  // °C
  minBiomass: number;        // biomass/tick below which organism loses health
  optimalBiomass: number;    // biomass/tick at which organism thrives
};

// ── Entity types ──────────────────────────────────────────────────────────────
export type Plant = {
  id: string;
  species: PlantSpecies;
  emoji: string;
  health: number;       // 0-100; 0 = dead
  growthRate: number;   // 0-100; declines under stress, rises in ideal conditions
  biomass: number;      // 0-100; food reserve available to organisms each tick
  requirements: PlantRequirements;
  x: number;            // % left position inside terrarium
  y: number;            // % top position inside terrarium
  animDelay: number;    // CSS animation-delay in seconds
};

export type Organism = {
  id: string;
  species: OrganismSpecies;
  emoji: string;
  health: number;          // 0-100
  consumptionRate: number; // biomass units consumed per tick
  wasteOutput: number;     // waste units generated per tick (reduced when starving)
  requirements: OrganismRequirements;
  x: number;
  y: number;
  animDelay: number;
};

// ── Environment (user-controlled + simulated) ─────────────────────────────────
export type EnvironmentState = {
  lighting: number;     // 0-100 — user slider
  humidity: number;     // 0-100 — user slider
  temperature: number;  // 5-40°C — user slider
  oxygen: number;       // 0-100 — generated by healthy plants each tick
  waste: number;        // 0-100 — produced by organisms, consumed by isopods, decays naturally
  moldRisk: number;     // 0-100 — rises with high humidity, eaten by springtails
};

// ── Event log entry ───────────────────────────────────────────────────────────
export type LogLevel = "info" | "warning" | "danger";

export type LogEntry = {
  id: string;
  tick: number;
  message: string;
  level: LogLevel;
};

// ── Full ecosystem state ──────────────────────────────────────────────────────
export type EcosystemState = {
  plants: Plant[];
  organisms: Organism[];
  environment: EnvironmentState;
  ecosystemHealth: number; // 0-100 global score
  tickCount: number;
  log: LogEntry[];
};
